export enum TasksActions {
    FETCH_TASKS = 'FETCH_TASKS',
    FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS',
    FETCH_TASKS_FAILURE = 'FETCH_TASKS_FAILURE',

    SET_TASK = 'SET_TASK',
    SET_TASK_SUCCESS = 'SET_TASK_SUCCESS',
    SET_TASK_FAILURE = 'SET_TASK_FAILURE',

    UPDATE_TASK = 'UPDATE_TASK',
    UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_FAILURE = 'UPDATE_TASK_FAILURE',

    DELETE_TASK = 'DELETE_TASK',
    DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS',
    DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE',

    CHECK_TAGS = 'CHECK_TAGS'
}
